<?php
/**
 * TL_ROOT/system/modules/easyupdate/languages/ru/default.php 
 * 
 * Contao extension: easyupdate 0.8.5 rc3 
 * Russian translation file 
 * 
 * Copyright : &copy; 2009 L.Schoening 
 * License   : LGPL 
 * Author    : Lutz Schoening (sawyer) 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['easyupdate']['0'] = "easyUpdate";
$GLOBALS['TL_LANG']['MOD']['easyupdate']['1'] = "Обновление Contao из панели управления.";
$GLOBALS['TL_LANG']['easyupdate']['backBT'] = "Назад";
$GLOBALS['TL_LANG']['easyupdate']['headline'] = "easyUpdate обновление Contao (текущая версия: %s)";
$GLOBALS['TL_LANG']['easyupdate']['selectfile'] = "Пожалуйста, выберите архив (ZIP-файл)";
$GLOBALS['TL_LANG']['easyupdate']['description'] = "Выберите архив из каталога (tl_files/easyupdate). Скрипт работает только с ZIP-архивами и не видит вложенные папки.";
$GLOBALS['TL_LANG']['easyupdate']['setfile'] = "Выбрать";
$GLOBALS['TL_LANG']['easyupdate']['files']['original'] = "Оригинальные файлы";
$GLOBALS['TL_LANG']['easyupdate']['files']['backup'] = "Файлы резервных копий";
$GLOBALS['TL_LANG']['easyupdate']['noupdate'] = "ИСКЛЮЧИТЬ файлы из обновления";
$GLOBALS['TL_LANG']['easyupdate']['demo'] = "Демо-файлы";
$GLOBALS['TL_LANG']['easyupdate']['config_legend'] = "Файлы конфигурации";
$GLOBALS['TL_LANG']['easyupdate']['other_legend'] = "Другие файлы";
$GLOBALS['TL_LANG']['easyupdate']['all'] = "Выбрать все";
$GLOBALS['TL_LANG']['easyupdate']['noupdatetext'] = "Вы можете выбрать файлы, ИСКЛЮЧАЕМЫЕ из обновления. В резервную копию войдут все файлы включая эти.";
$GLOBALS['TL_LANG']['easyupdate']['updatex'] = "версия (%s) ======> версия (%s)";
$GLOBALS['TL_LANG']['easyupdate']['update0'] = "Будет установлена старая версия Contao. Вы уверены в необходимости? Версия 2.7 имеет новые пароли, так что для обновление на более раннюю версию может быть не таким простым.";
$GLOBALS['TL_LANG']['easyupdate']['update1'] = "Вы установите более новую версию Contao.";
$GLOBALS['TL_LANG']['easyupdate']['update2'] = "Вы устанавливаете туже самую версию.";
$GLOBALS['TL_LANG']['easyupdate']['next'] = "Следующий шаг";
$GLOBALS['TL_LANG']['easyupdate']['previous'] = "Вернуться назад";
$GLOBALS['TL_LANG']['easyupdate']['changelog']['headline'] = "Список изменений между версиями %s и %s";
$GLOBALS['TL_LANG']['easyupdate']['changelog']['same'] = "Будет установлена таже версия, так что ничего не изменится.";
$GLOBALS['TL_LANG']['easyupdate']['changelog']['no'] = "Невозможно прочитать список изменений. За дополнительной информацией посетите сайт Contao (http://www.contao.org).";
$GLOBALS['TL_LANG']['easyupdate']['content'] = "Содержимое архива";
$GLOBALS['TL_LANG']['easyupdate']['backup'] = "Резервное копирование файлов";
$GLOBALS['TL_LANG']['easyupdate']['backuped'] = "Резервное копирование файлов";
$GLOBALS['TL_LANG']['easyupdate']['update'] = "Обновление ваших файлов";
$GLOBALS['TL_LANG']['easyupdate']['updated'] = "Обновлены:";
$GLOBALS['TL_LANG']['easyupdate']['skipped'] = "Пропущены:";
$GLOBALS['TL_LANG']['easyupdate']['error'] = "Ошибки:";
$GLOBALS['TL_LANG']['easyupdate']['exclude'] = "Исключены";
$GLOBALS['TL_LANG']['easyupdate']['readme']['headline'] = "Пожалуйста, прочтите это полностью, перед использованием";
$GLOBALS['TL_LANG']['easyupdate']['readme']['text1'] = "<h2>Обновление состоит из 4 шагов</h2> <ul><li>Получение списка файлов в архиве</li> <li>Резервное копирование имеющихся файлов</li> <li>Обновление файлов</li> <li>Запуск мастера установки</li></ul> Вполне возможно, что вам будет необходимо обновить базу данных. Если вы удалите файл конфигурации, пароль мастера установки: \"contao\"";
$GLOBALS['TL_LANG']['easyupdate']['readme']['text2'] = "<h2>Уведомление безопасности</h2> <ul><li>Ничто не является 100% безопасным. Смотрите, что вы делаете.</li> <li>Если вы не уверены, сделайте резервную копию базы данных, прежде чем использовать этот инструмент в первый раз.</li> <li>Инструмент изменяет тип файловой системы, возможна потеря данных.</li> <li>Вы делаете все на ваш страх и риск.</li></ul>";
$GLOBALS['TL_LANG']['easyupdate']['readme']['text3']['left'] = "<h2>Проверка и запуск</h2> <ul><li>2.5.x ====> 2.5.x</li> <li>2.5.x ====> 2.6.x</li> <li>2.5.x ====> 2.7.x</li> <li>2.6.x ====> 2.6.x</li> <li>2.6.x ====> 2.7.x</li> <li>2.7.x ====> 2.7.x</li> <li>2.7.x ====> 2.8.x</li></ul>";
$GLOBALS['TL_LANG']['easyupdate']['readme']['text3']['right'] = "<h2>Проверка и ошибка</h2> <ul><li>2.6.x ====> 2.5.x</li> <li>2.7.x ====> 2.5.x</li> <li>2.7.x ====> 2.6.x</li> <li>2.8.x ====> 2.5.x</li> <li>2.5.x ====> 2.6.x</li> <li>2.8.x ====> 2.7.x</li></ul>";
$GLOBALS['TL_LANG']['easyupdate']['readme']['text4'] = "Работа расширения была проверена на Contao версии 2.7.2, на более новой версии все тоже должно работать. Работа с версиями до 2.5 не проверялась, но вполне возможно, что они работают тоже. Если вы видите версию XXX, вполне возможно, что ZIP-архив поврежден.";
 
?>
